"""Evidence engine.

This is what makes Gantry AI reliable rather than merely fluent. Recommendations
are not generated by the language model. They are computed from outcomes in a
reference class of comparable historical cases, and ranked by the lower bound
of a Wilson score interval so that a response which worked 9 times out of 10 is
not ranked above one that worked 160 times out of 200.

Reference class selection follows the logic of reference class forecasting:
start from every case with the same diagnosed issue, then narrow by the
context the user gave (industry, methodology, contract) only while the class
stays large enough to support statistics.
"""

from dataclasses import dataclass

import numpy as np

from .utils import safe_float, sub, wilson_lower
from .vocab import INTERVENTIONS, ISSUES


@dataclass
class ReferenceClass:
    rows: np.ndarray
    description: str
    narrowed_by: list


def reference_class(index, issue_key, analysis, filters=None, min_cases=60):
    issue_code = index.code_of("critical_issue", ISSUES[issue_key]["name"])
    base = index.codes["critical_issue"] == issue_code
    for column, wanted in (filters or {}).items():
        if column in index.codes and wanted not in (None, "", []):
            values = wanted if isinstance(wanted, (list, tuple, set)) else [wanted]
            codes = [c for c in (index.code_of(column, v) for v in values) if c is not None]
            base &= np.isin(index.codes[column], codes)
    narrowed = []
    current = base
    steps = [("industry", analysis.industry), ("delivery_methodology", analysis.methodology),
             ("contract_type", analysis.contract)]
    for column, value in steps:
        if not value:
            continue
        code = index.code_of(column, value)
        trial = current & (index.codes[column] == code)
        if int(trial.sum()) >= min_cases:
            current = trial
            narrowed.append(value)
    rows = np.flatnonzero(current)
    label = ISSUES[issue_key]["name"].lower()
    desc = "{} cases of {}".format(len(rows), label)
    if narrowed:
        desc += " in " + ", ".join(narrowed)
    return ReferenceClass(rows=rows, description=desc, narrowed_by=narrowed)


def intervention_stats(index, rows, issue_key, min_n=8):
    """Outcome statistics for every intervention used in the reference class."""
    if len(rows) == 0:
        return [], 0.0
    int_codes = index.codes["intervention_strategy"][rows].astype(int)
    rec_labels = index.labels["recovery_success"]
    full_code = rec_labels.index("Full Recovery")
    not_code = rec_labels.index("Not Recovered")
    rec = index.codes["recovery_success"][rows]
    full = (rec == full_code).astype(float)
    anyrec = (rec != not_code).astype(float)
    n_labels = len(index.labels["intervention_strategy"])
    n = np.bincount(int_codes, minlength=n_labels)
    wins = np.bincount(int_codes, weights=full, minlength=n_labels)
    anys = np.bincount(int_codes, weights=anyrec, minlength=n_labels)
    lower = wilson_lower(wins, n)
    baseline = float(full.mean())

    sched = index.numeric["schedule_ratio"][rows]
    cost = index.numeric["cost_ratio"][rows]
    lead = index.numeric["intervention_lead_time_days"][rows]
    health = index.numeric["health_score"][rows]

    name_to_key = {v["name"]: k for k, v in INTERVENTIONS.items()}
    stats = []
    for code in np.flatnonzero(n >= min_n):
        sel = int_codes == code
        name = index.labels["intervention_strategy"][code]
        key = name_to_key[name]
        rate = wins[code] / n[code]
        stats.append({
            "intervention": name,
            "key": key,
            "cases": int(n[code]),
            "full_recovery_rate": safe_float(rate),
            "any_recovery_rate": safe_float(anys[code] / n[code]),
            "confidence_lower_bound": safe_float(lower[code]),
            "lift_vs_baseline": safe_float(rate / baseline if baseline > 0 else 0.0, 3),
            "median_schedule_ratio": safe_float(np.median(sched[sel]), 3),
            "median_cost_ratio": safe_float(np.median(cost[sel]), 3),
            "median_lead_time_days": safe_float(np.median(lead[sel]), 1),
            "mean_health_score": safe_float(np.mean(health[sel]), 1),
        })
    stats.sort(key=lambda s: (s["confidence_lower_bound"], s["cases"]), reverse=True)
    return stats, baseline


def timing_effect(index, rows, strong_names):
    """Compare full recovery for early versus late responses among the best interventions."""
    if len(rows) == 0 or not strong_names:
        return None
    codes = [index.code_of("intervention_strategy", n) for n in strong_names]
    codes = [c for c in codes if c is not None]
    sel = rows[np.isin(index.codes["intervention_strategy"][rows], codes)]
    if len(sel) < 30:
        return None
    lead = index.numeric["intervention_lead_time_days"][sel]
    full_code = index.labels["recovery_success"].index("Full Recovery")
    full = index.codes["recovery_success"][sel] == full_code
    cut = float(np.median(lead))
    early, late = full[lead <= cut], full[lead > cut]
    if len(early) < 10 or len(late) < 10:
        return None
    return {
        "threshold_days": safe_float(cut, 1),
        "early_full_recovery_rate": safe_float(early.mean()),
        "late_full_recovery_rate": safe_float(late.mean()),
        "early_cases": int(len(early)), "late_cases": int(len(late)),
    }


def outlook(index, rows):
    """Distribution of outcomes in the reference class, including P80 contingency guidance."""
    if len(rows) == 0:
        return {}
    cost = index.numeric["cost_ratio"][rows]
    sched = index.numeric["schedule_ratio"][rows]
    out_labels = index.labels["outcome_status"]
    counts = np.bincount(index.codes["outcome_status"][rows], minlength=len(out_labels))
    dist = {out_labels[i]: safe_float(counts[i] / len(rows)) for i in range(len(out_labels))}
    return {
        "cases": int(len(rows)),
        "outcome_distribution": dist,
        "median_cost_ratio": safe_float(np.median(cost), 3),
        "p80_cost_ratio": safe_float(np.quantile(cost, 0.8), 3),
        "median_schedule_ratio": safe_float(np.median(sched), 3),
        "p80_schedule_ratio": safe_float(np.quantile(sched, 0.8), 3),
        "suggested_cost_contingency_pct": safe_float(max(sub(float(np.quantile(cost, 0.8)), 1.0), 0.0) * 100, 1),
        "suggested_schedule_contingency_pct": safe_float(max(sub(float(np.quantile(sched, 0.8)), 1.0), 0.0) * 100, 1),
    }


def split_recommendations(stats, baseline, top=3):
    """Pick interventions to recommend and interventions to avoid."""
    recommend = [s for s in stats if s["full_recovery_rate"] > baseline
                 and s["confidence_lower_bound"] >= 0.75 * baseline][:top]
    if not recommend and stats:
        recommend = stats[:1]
    avoid = [s for s in stats
             if s["full_recovery_rate"] < 0.6 * baseline and s["cases"] >= 10]
    avoid.sort(key=lambda s: s["full_recovery_rate"])
    return recommend, avoid[:2]
